# Generated by Django 4.1.3 on 2022-12-08 20:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="دولة"
                    ),
                ),
                ("territory", models.CharField(max_length=100, verbose_name="إقليم")),
                ("county", models.CharField(max_length=100, verbose_name="مقاطعة")),
                ("region", models.CharField(max_length=100, verbose_name="منطقة")),
                ("city", models.CharField(max_length=100, verbose_name="مدينة")),
                (
                    "governorate",
                    models.CharField(max_length=100, verbose_name="محافظة"),
                ),
                ("village", models.CharField(max_length=100, verbose_name="قرية")),
                ("neighborhood", models.CharField(max_length=100, verbose_name="حي")),
                ("street", models.CharField(max_length=100, verbose_name="شارع")),
                ("building", models.IntegerField(default=0, verbose_name="بناية رقم")),
                ("floor", models.IntegerField(default=0, verbose_name="الدور")),
                ("unit", models.CharField(max_length=20, verbose_name="الوحدة")),
                (
                    "nearest_landmark",
                    models.CharField(max_length=150, verbose_name="أقرب معلم بارز"),
                ),
                (
                    "coordinates",
                    models.CharField(max_length=100, verbose_name="إحداثيات"),
                ),
                (
                    "landline_number",
                    models.CharField(max_length=20, verbose_name="هاتف رقم"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="جوال رقم"),
                ),
                (
                    "fax_number",
                    models.CharField(max_length=25, verbose_name="فاكس رقم"),
                ),
                ("telex", models.CharField(max_length=50, verbose_name="تلكس")),
                ("pobox", models.CharField(max_length=50, verbose_name="صندوق بريد")),
                (
                    "postal_code",
                    models.CharField(max_length=50, verbose_name="الرمز البريدي"),
                ),
                (
                    "email",
                    models.EmailField(max_length=150, verbose_name="البريد الإلكتروني"),
                ),
            ],
            options={
                "verbose_name": "ناشر",
                "verbose_name_plural": "الناشرون",
            },
        ),
    ]
