# Generated by Django 4.1.3 on 2022-12-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
            ],
            options={
                "verbose_name": "نوع وحدة",
                "verbose_name_plural": "انواع الوحدات",
            },
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="unit",
        ),
        migrations.AddField(
            model_name="publisher",
            name="unit_number",
            field=models.IntegerField(default=0, verbose_name="رقم الوحدة"),
        ),
        migrations.AddField(
            model_name="publisher",
            name="unit_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="publisher.unittype",
                verbose_name="نوع الوحدة",
            ),
        ),
    ]
