# Generated by Django 4.1.3 on 2022-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "publisher",
            "0002_unittype_remove_publisher_unit_publisher_unit_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="p_range",
            field=models.CharField(default="", max_length=100, verbose_name="النطاق"),
            preserve_default=False,
        ),
    ]
