# Generated by Django 4.1.3 on 2022-12-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("printinghouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printinghouse",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="printinghouse.branch",
                verbose_name="القسم",
            ),
        ),
    ]
