# Generated by Django 4.1.3 on 2022-12-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printinghouse', '0002_printinghouse_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printinghouse',
            options={'verbose_name': 'مطبعة', 'verbose_name_plural': 'المطابع'},
        ),
    ]
