# Generated by Django 4.1.3 on 2022-12-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printinghouse', '0003_alter_printinghouse_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printinghouse',
            name='deposit_number',
        ),
        migrations.RemoveField(
            model_name='printinghouse',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='printinghouse',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='printinghouse',
            name='issn',
        ),
        migrations.RemoveField(
            model_name='printinghouse',
            name='translation_isbn',
        ),
    ]
