# Generated by Django 4.1.3 on 2022-12-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0003_publisher_p_range'),
        ('printinghouse', '0004_remove_printinghouse_deposit_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم النشاط')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'المؤلفون',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'اﻷقسام',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='فئة المصنف')),
            ],
            options={
                'verbose_name': 'فئة المصنف',
                'verbose_name_plural': 'فئات المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
            },
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'محقق',
                'verbose_name_plural': 'المحققين',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم المجال')),
            ],
            options={
                'verbose_name': 'مجال',
                'verbose_name_plural': 'المجالات',
            },
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='اسم الصيغة')),
            ],
            options={
                'verbose_name': 'صيغة مصنف',
                'verbose_name_plural': 'صيغ المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الشكل')),
            ],
            options={
                'verbose_name': 'شكل مصنف',
                'verbose_name_plural': 'أشكال المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اللغة')),
            ],
            options={
                'verbose_name': 'لغة',
                'verbose_name_plural': 'اللغات',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='القياس')),
            ],
            options={
                'verbose_name': 'قياس مصنف',
                'verbose_name_plural': 'قياسات المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Mosannaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المصنف')),
                ('meaning', models.TextField(verbose_name='تفسير اسم المصنف')),
                ('date_published', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('parts_count', models.IntegerField(default=0, verbose_name='الأجزاء')),
                ('pages_count', models.IntegerField(default=0, verbose_name='الصفحات')),
                ('units_count', models.IntegerField(default=0, verbose_name='اﻷبواب')),
                ('chapters_count', models.IntegerField(default=0, verbose_name='الفصول')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموضوع')),
                ('unit', models.CharField(max_length=200, verbose_name='الباب')),
                ('branch', models.CharField(max_length=200, verbose_name='القسم')),
                ('sub_brnach', models.CharField(max_length=200, verbose_name='القسم الفرعي')),
                ('chapter', models.CharField(max_length=200, verbose_name='الفصل')),
                ('field', models.CharField(max_length=200, verbose_name='المجال')),
                ('activity', models.CharField(max_length=200, verbose_name='النشاط')),
                ('summary', models.TextField(verbose_name='نبذه عن المصنف')),
                ('image', models.ImageField(upload_to='أغلفة/', verbose_name='صورة المصنف')),
                ('file', models.FileField(upload_to='مصنفات/', verbose_name='ملف المصنف')),
                ('m_form', models.CharField(max_length=200, verbose_name='شكل المصنف')),
                ('m_size', models.CharField(max_length=200, verbose_name='حجم المصنف')),
                ('measurement', models.CharField(max_length=200, verbose_name='قياس المصنف')),
                ('preparation', models.CharField(max_length=200, verbose_name='إعداد')),
                ('author', models.CharField(max_length=200, verbose_name='تأليف')),
                ('checker', models.CharField(max_length=200, verbose_name='المحقق')),
                ('print_year', models.CharField(max_length=20, verbose_name='سنة الطباعة')),
                ('print_number', models.CharField(max_length=20, verbose_name='رقم الطباعة')),
                ('publish_year', models.CharField(max_length=20, verbose_name='سنة النشر')),
                ('isbn', models.CharField(max_length=50, verbose_name='ردمك')),
                ('issn', models.CharField(max_length=50, verbose_name='ردمد')),
                ('deposit_number', models.CharField(max_length=60, verbose_name='رقم الايداع')),
                ('iso', models.CharField(max_length=200, verbose_name='ايزو')),
                ('cover_artist', models.CharField(max_length=200, verbose_name='فنان الغلاف')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.category', verbose_name='فئة المصنف')),
                ('m_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.formats', verbose_name='صيغة المصنف')),
            ],
            options={
                'verbose_name': 'مصنف',
                'verbose_name_plural': 'المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'معد',
                'verbose_name_plural': 'المعدين',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الحجم')),
            ],
            options={
                'verbose_name': 'حجم مصنف',
                'verbose_name_plural': 'أحجام المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'المواضيع',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نوع المصنف')),
            ],
            options={
                'verbose_name': 'نوع المصنف',
                'verbose_name_plural': 'أنوع المصنفات',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='باب')),
            ],
            options={
                'verbose_name': 'باب',
                'verbose_name_plural': 'الأبواب',
            },
        ),
        migrations.CreateModel(
            name='TranslatedMosannaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_published', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار المترجم')),
                ('translate_publisher', models.CharField(max_length=200, verbose_name='ناشر الترجمة')),
                ('cover', models.ImageField(upload_to='Motargam/Covers', verbose_name='صورة المصنف المترجم')),
                ('tm_form', models.CharField(blank=True, max_length=200, null=True, verbose_name='شكل المصنف')),
                ('tm_size', models.CharField(max_length=100, verbose_name='حجم المصنف المترجم')),
                ('tm_mesaurement', models.CharField(max_length=100, verbose_name='قياس المصنف')),
                ('preparation', models.CharField(max_length=100, verbose_name='اعداد')),
                ('checker', models.CharField(max_length=200, verbose_name='المحقق')),
                ('print_year', models.CharField(max_length=20, verbose_name='سنة الطباعة')),
                ('print_number', models.CharField(max_length=20, verbose_name='رقم الطباعة')),
                ('publish_year', models.CharField(max_length=20, verbose_name='سنة النشر')),
                ('translation_isbn', models.CharField(max_length=50, verbose_name='ردمك الترجمة')),
                ('issn', models.CharField(max_length=50, verbose_name='ردمد')),
                ('deposit_number', models.CharField(max_length=60, verbose_name='رقم الايداع')),
                ('iso', models.CharField(max_length=200)),
                ('cover_artist', models.CharField(max_length=200, verbose_name='فنان الغلاف')),
                ('chain', models.CharField(max_length=100, verbose_name='السلسلة')),
                ('branch', models.CharField(max_length=100, verbose_name='القسم')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.lang', verbose_name='اللغة')),
                ('mosannaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosannaf.mosannaf', verbose_name='المصنف')),
                ('printing_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printinghouse.printinghouse', verbose_name='المطبعة')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.publisher', verbose_name='الناشر')),
                ('tm_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.formats', verbose_name='صيغة المترجم')),
            ],
            options={
                'verbose_name': 'مترجم مصنف',
                'verbose_name_plural': 'مترجمات المصنفات',
            },
        ),
        migrations.CreateModel(
            name='SubBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='القسم الفرعي')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosannaf.branch', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'قسم الفرعي',
                'verbose_name_plural': 'اﻷقسام الفرعية',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250, verbose_name='التقييم')),
                ('mosannaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosannaf_rate', to='mosannaf.mosannaf', verbose_name='المصنف')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='m_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.type', verbose_name='نوع المصنف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='original_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.lang', verbose_name='أصل لغة المصنف'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='printing_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printinghouse.printinghouse', verbose_name='المطبعة'),
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.publisher', verbose_name='ناشر'),
        ),
    ]
