# Generated by Django 4.1.3 on 2022-12-08 02:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0002_alter_lang_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="دولة"
            ),
        ),
    ]
