# Generated by Django 4.1.3 on 2022-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0003_alter_publisher_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="اسم الصيغة")),
            ],
            options={
                "verbose_name": "صيغة مصنف",
                "verbose_name_plural": "صيغ المصنفات",
            },
        ),
    ]
