# Generated by Django 4.1.3 on 2022-12-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0004_formats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="الشكل")),
            ],
            options={
                "verbose_name": "شكل مصنف",
                "verbose_name_plural": "أشكال المصنفات",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="الحجم")),
            ],
            options={
                "verbose_name": "حجم مصنف",
                "verbose_name_plural": "أحجام المصنفات",
            },
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="m_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.formats",
                verbose_name="صيغة المصنف",
            ),
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="m_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.forms",
                verbose_name="شكل المصنف",
            ),
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.size",
                verbose_name="حجم المصنف",
            ),
        ),
    ]
