# Generated by Django 4.1.3 on 2022-12-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0005_forms_size_mosannaf_m_format_mosannaf_m_form_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="القياس")),
            ],
            options={
                "verbose_name": "قياس مصنف",
                "verbose_name_plural": "قياسات المصنفات",
            },
        ),
    ]
