# Generated by Django 4.1.3 on 2022-12-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0006_measurement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
