# Generated by Django 4.1.3 on 2022-12-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0001_initial"),
        ("mosannaf", "0009_publisher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Publisher",
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="author",
            field=models.CharField(default="", max_length=200, verbose_name="تأليف"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="checker",
            field=models.CharField(default="", max_length=200, verbose_name="محقق"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="preparation",
            field=models.CharField(default="", max_length=200, verbose_name="اعداد"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="publisher.publisher",
                verbose_name="ناشر",
            ),
        ),
    ]
