# Generated by Django 4.1.3 on 2022-12-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0010_delete_publisher_mosannaf_author_mosannaf_checker_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
            ],
            options={
                "verbose_name": "مؤلف",
                "verbose_name_plural": "المؤلفون",
            },
        ),
        migrations.CreateModel(
            name="Checker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
            ],
            options={
                "verbose_name": "محقق",
                "verbose_name_plural": "المحققين",
            },
        ),
        migrations.CreateModel(
            name="Preparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
            ],
            options={
                "verbose_name": "معد",
                "verbose_name_plural": "المعدين",
            },
        ),
        migrations.AlterField(
            model_name="mosannaf",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.author",
                verbose_name="تأليف",
            ),
        ),
        migrations.AlterField(
            model_name="mosannaf",
            name="checker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.checker",
                verbose_name="المحقق",
            ),
        ),
        migrations.AlterField(
            model_name="mosannaf",
            name="preparation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.preparation",
                verbose_name="إعداد",
            ),
        ),
    ]
