# Generated by Django 4.1.3 on 2022-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0011_author_checker_preparation_alter_mosannaf_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosannaf",
            name="print_number",
            field=models.CharField(
                default="", max_length=20, verbose_name="رقم الطباعة"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="print_year",
            field=models.CharField(
                default="", max_length=20, verbose_name="سنة الطباعة"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mosannaf",
            name="publish_year",
            field=models.CharField(default="", max_length=20, verbose_name="سنة النشر"),
            preserve_default=False,
        ),
    ]
