# Generated by Django 4.1.3 on 2022-12-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0012_mosannaf_print_number_mosannaf_print_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="الاسم"
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل",
                "verbose_name_plural": "الفصول",
            },
        ),
    ]
