# Generated by Django 4.1.3 on 2022-12-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mosannaf", "0013_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosannaf",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mosannaf.chapter",
                verbose_name="الفصل",
            ),
        ),
    ]
