# Generated by Django 4.1.3 on 2022-12-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printinghouse', '0004_remove_printinghouse_deposit_number_and_more'),
        ('publisher', '0003_publisher_p_range'),
        ('mosannaf', '0014_mosannaf_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosannaf',
            name='isbn',
            field=models.CharField(default='', max_length=50, verbose_name='ردمك'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='printing_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printinghouse.printinghouse', verbose_name='المطبعة'),
        ),
        migrations.CreateModel(
            name='TranslatedMosannaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_publisher', models.CharField(max_length=200, verbose_name='ناشر الترجمة')),
                ('cover', models.ImageField(upload_to='تراجم/أغلفة', verbose_name='صورة المصنف المترجم')),
                ('size', models.CharField(max_length=100, verbose_name='حجم المصنف المترجم')),
                ('mesaurement', models.CharField(max_length=100, verbose_name='قياس المصنف')),
                ('preparation', models.CharField(max_length=100, verbose_name='اعداد')),
                ('checker', models.CharField(max_length=200, verbose_name='المحقق')),
                ('print_year', models.CharField(max_length=20, verbose_name='سنة الطباعة')),
                ('print_number', models.CharField(max_length=20, verbose_name='رقم الطباعة')),
                ('publish_year', models.CharField(max_length=20, verbose_name='سنة النشر')),
                ('translation_isbn', models.CharField(max_length=50, verbose_name='ردمك الترجمة')),
                ('issn', models.CharField(max_length=50, verbose_name='ردمد')),
                ('deposit_number', models.CharField(max_length=60, verbose_name='رقم الايداع')),
                ('iso', models.CharField(max_length=200)),
                ('cover_artist', models.CharField(max_length=200, verbose_name='فنان الغلاف')),
                ('chain', models.CharField(max_length=100, verbose_name='السلسلة')),
                ('branch', models.CharField(max_length=100, verbose_name='القسم')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosannaf.forms', verbose_name='شكل المصنف')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.lang', verbose_name='اللغة')),
                ('mosannaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosannaf.mosannaf', verbose_name='المصنف')),
                ('printing_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printinghouse.printinghouse', verbose_name='المطبعة')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.publisher', verbose_name='الناشر')),
                ('tm_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosannaf.formats', verbose_name='صيغة المترجم')),
            ],
            options={
                'verbose_name': 'مترجم مصنف',
                'verbose_name_plural': 'مترجمات المصنفات',
            },
        ),
    ]
