# Generated by Django 4.1.3 on 2022-12-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0015_mosannaf_isbn_mosannaf_printing_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedmosannaf',
            name='cover',
            field=models.ImageField(upload_to='مترجم/أغلفة/', verbose_name='صورة المصنف المترجم'),
        ),
    ]
