# Generated by Django 4.1.3 on 2022-12-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0016_alter_translatedmosannaf_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedmosannaf',
            name='cover',
            field=models.ImageField(upload_to='Motargam/Covers', verbose_name='صورة المصنف المترجم'),
        ),
    ]
