# Generated by Django 4.1.3 on 2022-12-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0017_alter_translatedmosannaf_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosannaf',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='translatedmosannaf',
            name='form',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شكل المصنف'),
        ),
    ]
