# Generated by Django 4.1.3 on 2022-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0018_alter_mosannaf_subject_alter_translatedmosannaf_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosannaf',
            name='size',
        ),
        migrations.RemoveField(
            model_name='mosannaf',
            name='sub_branch',
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='m_size',
            field=models.CharField(default='', max_length=200, verbose_name='حجم المصنف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosannaf',
            name='sub_brnach',
            field=models.CharField(default='', max_length=200, verbose_name='القسم الفرعي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='activity',
            field=models.CharField(default='', max_length=200, verbose_name='النشاط'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='author',
            field=models.CharField(default='', max_length=200, verbose_name='تأليف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='branch',
            field=models.CharField(default='', max_length=200, verbose_name='القسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='chapter',
            field=models.CharField(default='', max_length=200, verbose_name='الفصل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='checker',
            field=models.CharField(default='', max_length=200, verbose_name='المحقق'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='field',
            field=models.CharField(default='', max_length=200, verbose_name='المجال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='m_form',
            field=models.CharField(default='', max_length=200, verbose_name='شكل المصنف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='measurement',
            field=models.CharField(default='', max_length=200, verbose_name='قياس المصنف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='preparation',
            field=models.CharField(default='', max_length=200, verbose_name='إعداد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mosannaf',
            name='unit',
            field=models.CharField(default='', max_length=200, verbose_name='الباب'),
            preserve_default=False,
        ),
    ]
