# Generated by Django 4.1.3 on 2022-12-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0019_remove_mosannaf_size_remove_mosannaf_sub_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=500, verbose_name='التقييم')),
                ('mosannaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosannaf.mosannaf', verbose_name='المصنف')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
    ]
