# Generated by Django 4.1.3 on 2022-12-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0020_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='mosannaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosannaf_rate', to='mosannaf.mosannaf', verbose_name='المصنف'),
        ),
    ]
