# Generated by Django 4.1.3 on 2022-12-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosannaf', '0021_alter_rate_mosannaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='details',
            field=models.CharField(max_length=250, verbose_name='التقييم'),
        ),
    ]
